name: JSAN-Index
version: 0.01_01
abstract: A Class::DBI wrapper for the SQLite JSAN Index
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  File::Spec: 0.80
  Test::More: 0.47
requires:
  perl: 5.005
  JSAN::Index::Data: 0
  Class::DBI: 0.96
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
